### ISSUE TITLE
[Feature Request] Place blocks with same orientation

### ISSUE THREAD

**Issue by AngleWyrm10** [nicguzzo/wands#10]
As can be seen in this screenshot, when I used the up button to place a spruce log above another spruce log, the orientation of the newly placed log was different from the original.

![featureRequest](https://user-images.githubusercontent.com/55937426/135439296-0cf22947-bc0f-404e-9b57-2ce549c04eb6.png)

**Comment by nicguzzo** [comment]
that's intended, you must select the axis, for logs and pillars

**Comment by nicguzzo** [comment]
although, as previous versions of the mod respected the state, I will add another option, if no axis is selected, then use same axis as the source block.
