### ISSUE TITLE
Screen not registered for screen handler wands:wand_menu!

### ISSUE THREAD

**Issue by robhawkes** [nicguzzo/wands#11]
Trying out the wands for the first time but currently unable to open the wand menu. Here are some details that'll hopefully help to debug it, and let me know if you need anything else from me.

## Versions
- Java 1.17.1
- Fabric 0.11.6
- Building Wands 2.2.5
- Quite a few other mods

## Issue
- Press the wand menu key and nothing happens in game
- Check the logs and each time the key is pressed the following is output
```
[09:06:19] [Render thread/ERROR]: ########## GL ERROR ##########
[09:06:19] [Render thread/ERROR]: @ Render
[09:06:19] [Render thread/ERROR]: 65539: Invalid key -1
[09:06:20] [Render thread/WARN]: Screen not registered for screen handler wands:wand_menu!
```

**Comment by crysthala** [comment]
Okay, I have removed each of these mods one by one to see what happens, and I've ruled out the following as potential culprits: Cloth Config API (at least the standalone file), Data Attributes, Carpet Mod, and Patchouli.

So we're left with Dawn API, Impersonate, Industrial Revolution, Megane, Mod Menu, Player Ability Lib, Pehkui, Somnus, Trinkets, and Yung's API. Architectury, Fabric API, Fabric Language Kotlin, and WTHIT also have to be in there as dependencies, but they don't break anything.

**Comment by nicguzzo** [comment]
it's weired, if I remove all the other mods but trinkets, Building Wands, and deps), then it works ok. it must be trinkets+other mod.

**Comment by crysthala** [comment]
Removing any one of the mods I listed fixes it for me, but I'm really at a loss as to why. I'm going through the .jars looking for access wideners and mixins they seem to share, since it's my understanding those are common culprits in compatibility issues.
