### ISSUE TITLE
Crash caused by attempting to render modded blocks?

### ISSUE THREAD

**Issue by shinjitumala** [nicguzzo/wands#14]
I accidentally clicked on a modded block using a building wand, and the game crashed.
The game seems to have crashed because it tried to render a "ghost" block of a modded block and it had an illegal state, according to the mod.

Could there be a way to blacklist modded blocks from being rendered as ghost blocks?

More details in the issue I submitted on the other mod that is conflicting with this one;
[https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5648](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5648).

**Comment by nicguzzo** [comment]
I'll fix this asap. Meanwhile you can disable ghost_blocks by setting fancy_preview=false in config

**Comment by nicguzzo** [comment]
@shinjitumala please try the new version 2.2.9beta of the building wands, I had to add a try catch to the getQuads invocation, it's not pretty but until ae2 fix it to return an empty list it will have to do. I also improved the denied blocks list to not process any blocks in the list and I've added the cable_bus to it but I guess there are more.

**Comment by shinjitumala** [comment]
@nicguzzo Thank you very much for the timely fix. I have confirmed that the crash no longer occurs with the new beta version.

It is worth mentioning that the AE2 devs also changed their code such that the exception won't be thrown anymore.
