### ISSUE TITLE
place blocks with shift click -> break it -> item not stacking

### ISSUE THREAD

**Issue by MSandro** [nicguzzo/wands#15]
Hello, I have spend a lot of time to figure out what mod is causing this annoying behaviour in my Modpack.
when I place a block while sneaked, it adds a tag to the stack in my hand. Once I break the placed block it doesn't stack because it has not got this empty tag{} attribute. Please fix this.

**Comment by MSandro** [comment]
I downgraded to BuildingWands-2.2.7_mc1.17.1-fabric.jar, this version doesn't cause the problem.

**Comment by nicguzzo** [comment]
fixed on latest beta for fabric
