### ISSUE TITLE
what does "wand offhand can't have tag" mean

### ISSUE THREAD

**Issue by a6entoren6e** [nicguzzo/wands#16]
and how do i stop it from filling chat every time i use the wand?

**Comment by a6entoren6e** [comment]
![2021-12-28_18 54 54](https://user-images.githubusercontent.com/96801124/147615597-14b65ad9-daf1-4c42-a63e-b0ebb6da783b.png)

**Comment by nicguzzo** [comment]
Yeah, I keep forgetting to remove that. It's from previous versions.

**Comment by nicguzzo** [comment]
I'll remove it for next version

**Comment by a6entoren6e** [comment]
oh ok. i turned off chat so its no big deal. i was like wtf did i do? because it wasn't doing that at first. great mod though
