### ISSUE TITLE
Concerned about Warning in Log

### ISSUE THREAD

**Issue by greensad** [nicguzzo/wands#18]
Skipped language file: wands:lang/en_us.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 115 column 4 path $.screen.wands.conf)

**Log:** https://paste.ee/p/0ZBus

**Comment by nicguzzo** [comment]
Thanks, I bet that's the problem that´s breaking all my labels, haha. I'll fix that asap.

**Comment by nicguzzo** [comment]
Fixed
