### ISSUE TITLE
Can't break Glowstone in survival

### ISSUE THREAD

**Issue by Bluetinity** [nicguzzo/wands#42]
Blocks like Glowstone don't have a specific tool, so you can't use the wand to break these in survival, but other blocks like that ex. Glass break just fine.

**Comment by nicguzzo** [comment]
you can add any block not tool specific to wands.json so it can be broken with pickaxe or other vanilla tools, you can also deny a spcific block in str_denied

"str_pickaxe_allowed": [
    "minecraft:sea_lantern",
    "minecraft:glowstone"
  ],
str_axe_allowed": [],
  "str_shovel_allowed": [],
  "str_hoe_allowed": [
    "minecraft:moss_block"
  ],
  "str_shears_allowed": [
    "minecraft:moss_block"
  ],
  "str_denied": []
