### ISSUE TITLE
Grid keeps increasing its size without me doing anything

### ISSUE THREAD

**Issue by docHP** [nicguzzo/wands#43]
![image](https://github.com/nicguzzo/wands/assets/44784448/45e72b42-2465-4d5b-b015-09f87f2bd0b6)
![image](https://github.com/nicguzzo/wands/assets/44784448/0d4e4dbe-533c-4efe-a016-234ad0b1eb11)

All I did was open the menu then close it again.

**Comment by Mc-man165** [comment]
@docHP Did you solve this issue? I'm having it now and not able to reset the wand back down even after a reboot.
