### ISSUE TITLE
Destruction and/or Replace Wand?

### ISSUE THREAD

**Issue by SgtD4rk** [nicguzzo/wands#5]
I know it must be hard mantaining this project but i really like this mod for building in creative it helps a lot if u add 1 or both

**Comment by nicguzzo** [comment]
Destruction mode is already done, at least on newer versions, you need a tool in the offhand to enable this mod, a red outline indicates the targeted blocks, it also works with the palette on the offhand, but the tool must be on the first slot of the inventory in this case. I'm working on a replace mode next, stay tuned... Also on the wiki to document better all the modes and stuff
