### ISSUE TITLE
Crash with Modern Industrialization

### ISSUE THREAD

**Issue by sirben99** [nicguzzo/wands#8]
Minecraft: 1.17.1
Fabric-Api: 0.40.1+1.17
Building Wands: 2.2.2-fabric
Architectury: 2.5.27-fabric
Modern Industrialization: 0.5.12
Cloth Config: 5.0.38-fabric
Roughly Enough Items: 6.0.279-alpha-fabric

Other mods: No

Hey!

I have an issue where when trying to look at an fluid pipe from Modern Industrialization the game crashes. I saw someone mention it happens with some machines too, but havent tested those my self.

You should also link this issue page to Curseforge and add Architectury as a dependency

Crash report:
https://pastebin.com/VBFdPBgS

Log:
https://pastebin.com/8fQNB6DJ

If you reguire any more info let me know!

Ben

**Comment by nicguzzo** [comment]
fixed on version 2.2.3
